window.RELEASES_DATA = [
    {
        id: "9",
        number: "01",
        title: "9",
        year: "2022",
        format: "Single",
        label: "Stasis Sound",
        trackCount: 1,
        artworkRef: "assets/releases/release-01-9.jpg",
        artworkCredit: "Tom Gregory",
        mixCredit: "Robin Tetlow-Shooter",
        masterCredit: "Robin Tetlow-Shooter",
        tracks: [
            { title: "9", duration: "03:53" }
        ]
    },
    {
        id: "exstasis-2023",
        number: "02",
        title: "Exstasis",
        year: "2023",
        format: "Album",
        label: "Mizuha 罔象",
        trackCount: 11,
        artworkRef: "assets/releases/release-02-exstasis.jpg",
        artworkCredit: "Simon",
        mixCredit: "Azrel",
        masterCredit: "Wim Daehan",
        tracks: [
            { title: "Mist Shield", duration: "2:53" },
            { title: "Radiance", duration: "2:49" },
            { title: "Breath", duration: "3:28" },
            { title: "Emerald Vizor", featuredArtists: "Yoshitaka Hikawa", duration: "4:54" },
            { title: "Sheath-Winged", featuredArtists: "Renko", duration: "3:47" },
            { title: "Shishigami", duration: "2:40" },
            { title: "Black Luster", duration: "2:49" },
            { title: "Cordyceps", duration: "4:25" },
            { title: "Frozen Filter", duration: "2:24" },
            { title: "Mōryō", featuredArtists: "Yoyou", duration: "4:36" },
            { title: "Dryad", duration: "4:17" }
        ]
    },
    {
        id: "exstasis-restored-2024",
        number: "03",
        title: "Exstasis: Restored",
        year: "2024",
        format: "Album",
        label: "Mizuha 罔象",
        trackCount: 11,
        artworkRef: "assets/releases/release-03-exstasis-restored.jpg",
        artworkCredit: "Kazuma Watanabe",
        mixCredit: "Azrel",
        masterCredit: "Lorenzi",
        tracks: [
            { title: "Distil", duration: "4:45" },
            { title: "Radiance", remixBy: "Quit Life", duration: "3:45" },
            { title: "Cordyceps", remixBy: "TCV", duration: "4:01" },
            { title: "Dryad", remixBy: "Parasol", duration: "2:43" },
            { title: "Radiance", remixBy: "Lorenzi", duration: "2:34" },
            { title: "Frozen Filter", remixBy: "Sun Angels", duration: "1:22" },
            { title: "Black Luster", remixBy: "Takemasa", duration: "5:21" },
            { title: "Sheath-Winged", featuredArtists: "Renko", remixBy: "s7n", duration: "4:10" },
            { title: "Shishigami", remixBy: "Soichi 芳芽", duration: "3:20" },
            { title: "Mōryō", featuredArtists: "Yoyou", kenjaRebuildBy: "Ichiro Tanimoto", duration: "4:02" },
            { title: "Solar Sail", duration: "6:30" }
        ]
    },
    {
        id: "exstasis-restored",
        number: "04",
        title: "re.gen",
        year: "2024",
        format: "Expanded Edition",
        label: "Stasis Sound",
        trackCount: 14,
        artworkRef: "assets/releases/release-04-exstasis-restored.jpg",
        artworkCredit: "TBC",
        mixCredit: "TBC",
        masterCredit: "TBC",
        tracks: [
            { title: "Signal Veil (Restored)", duration: "05:06" },
            { title: "Glass Divide", duration: "05:03" },
            { title: "After Current", duration: "06:26" },
            { title: "Delta Nights", duration: "03:55" },
            { title: "Subtle Engine", duration: "05:47" },
            { title: "Nocturne Lift", duration: "04:09" },
            { title: "Far Relay", duration: "06:02" },
            { title: "Hollow Thread", duration: "04:33" },
            { title: "Blue Static", duration: "05:31" },
            { title: "Open End", duration: "07:19" },
            { title: "Afterglow System", duration: "04:42" },
            { title: "Pulse Archive", duration: "05:11" },
            { title: "Quiet Spill", duration: "03:37" },
            { title: "Static Reprise", duration: "06:21" }
        ]
    },
    {
        id: "boreal-relay",
        number: "05",
        title: "Boreal Relay",
        year: "2025",
        format: "EP",
        label: "Stasis Sound",
        trackCount: 6,
        artworkRef: "assets/releases/release-05-boreal-relay.jpg",
        artworkCredit: "TBC",
        mixCredit: "TBC",
        masterCredit: "TBC",
        tracks: [
            { title: "Northbound Delay", duration: "04:39" },
            { title: "Iceline", duration: "05:18" },
            { title: "Pale Generator", duration: "03:51" },
            { title: "Mirror Drift", duration: "06:04" },
            { title: "Relay Static", duration: "04:26" },
            { title: "White Horizon", duration: "07:08" }
        ]
    },
    {
        id: "quiet-geometry",
        number: "06",
        title: "Quiet Geometry",
        year: "2026",
        format: "Album",
        label: "Stasis Sound",
        trackCount: 11,
        artworkRef: "assets/releases/release-06-quiet-geometry.jpg",
        artworkCredit: "TBC",
        mixCredit: "TBC",
        masterCredit: "TBC",
        tracks: [
            { title: "Contour Room", duration: "05:14" },
            { title: "Clear Segment", duration: "04:07" },
            { title: "Slow Mirror", duration: "06:28" },
            { title: "Still Voltage", duration: "03:52" },
            { title: "Hollow Arc", duration: "05:05" },
            { title: "Near White", duration: "04:39" },
            { title: "Vector Bloom", duration: "05:42" },
            { title: "Drift Axis", duration: "04:58" },
            { title: "Quiet Geometry", duration: "06:11" },
            { title: "Line Memory", duration: "03:47" },
            { title: "Residual Light", duration: "07:03" }
        ]
    }
];
